services:
  - type: web
    name: laravel-web
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan migrate --force --seed
      php artisan serve --host=0.0.0.0 --port=$PORT

  - type: worker
    name: laravel-queue
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan queue:work --tries=3

  - type: worker
    name: laravel-reverb
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan reverb:start
